### ISSUE TITLE
Dude you finally did it :D But I have a small issue 

### ISSUE THREAD

**Issue by LeFEAR** [nomyownnet/cert-asa-install#1]
So I am running other 2 web servers at port 80 
and I quote clueless how to make the distinction between A , B , C server , 
do you have any ideas ?
thank you 
Also amazing job that you finally did the thing the other guy couldn't patch up his DNS thing that they stopped using :D 
Thanks again

**Comment by nomyownnet** [comment]
1. You can use different NAT translation records on ASA with source addresses "lets encrypt" project. But I am not sure in this variant.
2. Use different virtual hosts on your web-server.
For instance
https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/

**Comment by LeFEAR** [comment]
okay I will have a look , 
also the API user with cleartext creds is not really ideal and needs ( 15 level ) in order to work .. 
there should be an other way 
thnx
