### ISSUE TITLE
Manual convert and install.

### ISSUE THREAD

**Issue by woodie** [nomyownnet/cert-asa-install#9]
As there are a lot of moving parts here, it would be helpful to document how to manually convert and install a cert into the ASA. I assume the conversion is something like this:

openssl pkcs12 -export -inkey privkey.pem -in cert.pem -name "vpn.domain.com.ar" -out cert.p12

**Comment by nomyownnet** [comment]
It doesn't make sense as there is enough info how to do it manually on the net. The aim of the script was to automate the routine, not to save the secret knowledge. 

But if you want to prepare a PR, you are welcome any time. :)
